package com.importio.api.clientlite.data;

import java.util.UUID;

import lombok.AccessLevel;
import lombok.Data;
import lombok.experimental.FieldDefaults;

/**
 * A QueryMessage contains the data payload from import.io servers that provide application-level details
 * on what is happening on the servers (rather than connection-level details like in {@see ResponseMessage}) with
 * regards to user-issued queries.
 * 
 * @author dev@import.io
 * @see https://github.com/import-io/importio-client-libs/tree/master/java
 */
@Data
@FieldDefaults(level=AccessLevel.PRIVATE)
public class QueryMessage {

	/**
	 * The type of message being returned by the query system
	 */
	public static enum MessageType {
		// A job has been initialised on behalf of the user
		INIT,
		// A job is in progress and a message has been generated
		MESSAGE,
		// A job has finished
		STOP,
		// There has been an error returned by a job (e.g. external site errored)
		ERROR,
		// A job's work has been started
		START,
		// The user is not authenticated
		UNAUTH,
		// A new set of jobs has been spawned
		SPAWN, 
		// A job has been cancelled
		CANCEL,
		// The client has disconnected while the query was in progress
		DISCONNECT
	}

	/**
	 * The type of this message, for more details {@see MessageType}
	 */
	MessageType type;
	
	/**
	 * Any data that has been sent along with the message (e.g. query results)
	 */
	Object data;
	
	/**
	 * The query ID that this message is associated with
	 */
	UUID queryId;
	
	/**
	 * An execution ID is generated by the server for jobs
	 */
	UUID executionId;
	
	/**
	 * The ID of the request this message is replying to, this refers to the {@link Query#getRequestId()} field of the input query
	 */
	String requestId;
	
	/**
	 * The number of remaining messages the server expects to send
	 */
	Integer messagesRemaining;
	
	/**
	 * The GUID of the connector that this result has originated from
	 */
	UUID connectorGuid;
	
	/**
	 * The GUID of the connector's version that this result has originated from
	 */
	UUID connectorVersionGuid;
}
