# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bddabf4b421a5345685f5e86fcb12e01b3e2528c1b63bd2ee6fb9126e9032148cf67cc01bd4b24b62c5eb895342e0ae9b011067872c02e586892ed894b42e0d8

test:
  secret_key_base: 47933fd2d2d3bee0982751c057fad1e503104c6f0d7648981e57c962cd9a480d8f7f14e9bba343c6b8502e124e119a2440f89772e0437a75e470c2b810fabcc1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
